config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sessions/new"
  get  "/help", to: "static_pages#help"
  get  "/about", to: "static_pages#about"
  get  "/contact", to: "static_pages#contact"
  get  "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "password_resets/new"
  get "password_resets/edit"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(show index destroy)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "footer_text_html", main_href: link_to(t("tutorial"), t("url.main_page")),
      author_href: link_to(t("author"), t("url.author")) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("about"), about_path %></li>
      <li><%= link_to t("contact"), contact_path %></li>
      <li><%= link_to t("news"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("sample_app"), root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users"), users_path %></li>
          <li class="dropdown">
            <%= link_to t("acc_html"), "#", "data-toggle": "dropdown", class: "dropdown-toggle" %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: Settings.avatar_small), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    <%= t "posted_ago", time_ago: time_ago_in_words(micropost.created_at) %>
     <% if current_user?(micropost.user) %>
      <%= link_to t("delete"), micropost, method: :delete,
        data: {confirm: t("you_sure")} %>
    <% end %>
  </span>
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>